-- Run this once in Supabase: SQL Editor → New query → Run
--
-- Creates a public guestbook table. Visitors post with name + message only.
-- No account required. You can delete spam from Table Editor in the dashboard.

create table if not exists guestbook_comments (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  message text not null check (char_length(message) between 1 and 1000),
  created_at timestamptz default now() not null,
  approved boolean default true not null
);

alter table guestbook_comments enable row level security;

create policy "Anyone can read approved comments"
  on guestbook_comments for select
  using (approved = true);

create policy "Anyone can leave a comment"
  on guestbook_comments for insert
  with check (true);

-- Optional: require moderation before comments appear publicly.
-- Change the default and update the read policy:
--
-- alter table guestbook_comments alter column approved set default false;
-- drop policy "Anyone can read approved comments" on guestbook_comments;
-- create policy "Anyone can read approved comments"
--   on guestbook_comments for select using (approved = true);
